# values.yaml

architecture: replication
diagnosticMode.enabled: false

global:
  redis:
    password: "redis-password"
##
auth.enabled: false
auth.sentinel: false
##
master:
  persistence: 
    enabled: false
##
replica:
  replicaCount: 3
  persistence: 
    enabled: false
##
sentinel:
  enabled: true
  persistence:  
    enabled: false
